//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.APP_CODE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_PAYEE_MST
    {
        public string AP_DESC { get; set; }
    }
}
