//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.APP_CODE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUE_BOOK_MST
    {
        public string GL_CODE { get; set; }
        public int CHQ_BOOK_NO { get; set; }
        public string PREFIX_LEAF { get; set; }
        public Nullable<int> NO_OF_LEAF { get; set; }
        public Nullable<int> START_DIGIT { get; set; }
        public Nullable<bool> CHEQUE_BOOK_ACTIVE { get; set; }
    }
}
