//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.APP_CODE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUE_BOOK_DET
    {
        public string GL_CODE { get; set; }
        public int CHQ_BOOK_NO { get; set; }
        public string CHEQUE_NO { get; set; }
        public Nullable<bool> USED { get; set; }
        public string HOLD { get; set; }
    }
}
