//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.APP_CODE
{
    using System;
    using System.Collections.Generic;
    
    public partial class FISCAL_YEAR
    {
        public string FISCAL_YEAR_ID { get; set; }
        public Nullable<System.DateTime> DATE_FROM { get; set; }
        public Nullable<System.DateTime> DATE_TO { get; set; }
        public string PREVIOUS_YEAR { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
    }
}
