//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.APP_CODE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_MST
    {
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
        public Nullable<System.DateTime> SYSTEM_TIME { get; set; }
        public string USER_ID { get; set; }
        public int COM_CODE { get; set; }
        public int PRIN_CODE { get; set; }
        public int LOC_CODE { get; set; }
        public int FISCAL_YEAR_ID { get; set; }
        public int V_TYPE { get; set; }
        public int VOUCHER_NO { get; set; }
        public Nullable<System.DateTime> V_DATE { get; set; }
        public string CB_CREDIT { get; set; }
        public string CHEQUE_NO { get; set; }
        public Nullable<System.DateTime> CHEQUE_DATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<bool> USED { get; set; }
        public string REMARKS { get; set; }
        public Nullable<bool> RECONCILE { get; set; }
        public Nullable<bool> POST_FLAG { get; set; }
        public Nullable<int> SUPP_CODE { get; set; }
        public Nullable<decimal> GROSS_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_TAX { get; set; }
        public string PAYMENT_TYPE { get; set; }
        public string ADV_NO_PO_NO { get; set; }
        public Nullable<int> CUST_CODE { get; set; }
        public string ACC_PAYABLE { get; set; }
        public Nullable<bool> CANCEL_FLAG { get; set; }
        public Nullable<int> VENDOR_GROUP { get; set; }
        public string NEW_PAYABLE { get; set; }
        public string JOB_COM { get; set; }
        public string JOB_PRIN { get; set; }
        public string JOB_LOC { get; set; }
        public string JOB_YEAR { get; set; }
        public string JOB_TYPE { get; set; }
        public string JOB_NO { get; set; }
        public string PAYMENT_THROUGH_SYSTEM { get; set; }
        public string PO_COM { get; set; }
        public string PO_PRIN { get; set; }
        public string PO_LOC { get; set; }
        public string PO_YEAR { get; set; }
        public string PO_TYPE { get; set; }
        public string PO_NO { get; set; }
    }
}
