//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.APP_CODE
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TYPE
    {
        public Nullable<int> ID { get; set; }
        public string V_TYPE1 { get; set; }
        public string DESCRIPTION { get; set; }
        public string TYPE_GROUP { get; set; }
        public string CVT { get; set; }
        public string CASHBANK { get; set; }
    }
}
